# Generated by Django 6.1.1 on 2026-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Brandon Herford', max_length=120)),
                ('tagline', models.CharField(blank=True, help_text='Short one-liner shown under your name on the home page.', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Longer intro (Markdown supported) for the home page.')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('dribbble_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Full URL to your X/Twitter profile.')),
                ('resume', models.FileField(blank=True, help_text='PDF resume.', upload_to='resume/')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/')),
                ('og_image', models.ImageField(blank=True, help_text='Default social-share preview image (1200x630 recommended).', upload_to='og/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
    ]
