# Generated by Django 6.1.1 on 2026-09-30 01:19

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(help_text='Post content in Markdown. Use the toolbar to format and upload images inline.'),
        ),
    ]
