# Generated by Django 6.1.1 on 2026-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short description shown on the portfolio card.', max_length=280)),
                ('description', models.TextField(blank=True, help_text='Full write-up (Markdown supported).')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/')),
                ('url', models.URLField(blank=True, help_text='Live site / demo link.')),
                ('source_url', models.URLField(blank=True, help_text='Source code link (e.g. GitHub).')),
                ('tech', models.CharField(blank=True, help_text="Comma-separated tech, e.g. 'Django, p5.js, PostgreSQL'.", max_length=240)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured projects surface on the home page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-year', 'title'],
            },
        ),
    ]
