# Generated by Django 6.1.1 on 2026-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=160)),
                ('company', models.CharField(max_length=160)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current role.', null=True)),
                ('description', models.TextField(blank=True, help_text='What you did / achievements (Markdown supported).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework / Library'), ('tool', 'Tool'), ('design', 'Design'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
